import type { Appointment, MedicalRecord, Bill, PatientVitals, NursingTask, PharmacyOrder, Medication, AmbulanceTrip, Ambulance, AmbulanceRequest } from "./types"

// Mock appointments data
export const mockAppointments: Appointment[] = [
  {
    id: "apt1",
    patientId: "p1",
    patientName: "John Doe",
    doctorId: "d1",
    doctorName: "Dr. Sarah Smith",
    date: "2025-10-05",
    time: "10:00 AM",
    type: "consultation",
    status: "scheduled",
    reason: "Regular checkup",
  },
  {
    id: "apt2",
    patientId: "p1",
    patientName: "John Doe",
    doctorId: "d2",
    doctorName: "Dr. Michael Johnson",
    date: "2025-10-10",
    time: "2:00 PM",
    type: "follow-up",
    status: "scheduled",
    reason: "Follow-up on blood pressure",
  },
  {
    id: "apt3",
    patientId: "p2",
    patientName: "Jane Smith",
    doctorId: "d1",
    doctorName: "Dr. Sarah Smith",
    date: "2025-09-28",
    time: "11:00 AM",
    type: "consultation",
    status: "completed",
    reason: "Chest pain evaluation",
  },
]

// Mock medical records
export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "mr1",
    patientId: "p1",
    doctorId: "d1",
    date: "2025-09-15",
    diagnosis: "Hypertension Stage 1",
    symptoms: ["Headache", "Dizziness", "Fatigue"],
    prescription: [
      {
        id: "rx1",
        medication: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        instructions: "Take in the morning with water",
      },
    ],
    labResults: [
      {
        id: "lab1",
        testName: "Blood Pressure",
        result: "145/92 mmHg",
        normalRange: "120/80 mmHg",
        date: "2025-09-15",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to reduce sodium intake and increase physical activity.",
    followUpDate: "2025-10-15",
  },
]

// Mock billing data
export const mockBills: Bill[] = [
  {
    id: "bill1",
    patientId: "p1",
    patientName: "John Doe",
    date: "2025-09-15",
    items: [
      {
        id: "item1",
        description: "Consultation Fee",
        quantity: 1,
        unitPrice: 100,
        total: 100,
      },
      {
        id: "item2",
        description: "Blood Pressure Test",
        quantity: 1,
        unitPrice: 25,
        total: 25,
      },
    ],
    subtotal: 125,
    tax: 12.5,
    total: 137.5,
    status: "paid",
    paymentMethod: "Credit Card",
  },
]

// Mock vitals data for nurse module
export const mockPatientVitals: PatientVitals[] = [
  {
    id: "vitals1",
    patientId: "p1",
    patientName: "John Doe",
    nurseId: "n1",
    nurseName: "Nurse Emma Wilson",
    date: "2025-10-05",
    time: "09:30 AM",
    temperature: 98.6,
    bloodPressure: "120/80",
    heartRate: 72,
    respiratoryRate: 16,
    bloodOxygen: 98,
    weight: 75,
    height: 180,
    bmi: 23.1,
    notes: "Patient stable, vitals normal",
  },
  {
    id: "vitals2",
    patientId: "p2",
    patientName: "Jane Smith",
    nurseId: "n1",
    nurseName: "Nurse Emma Wilson",
    date: "2025-10-05",
    time: "10:15 AM",
    temperature: 99.2,
    bloodPressure: "128/85",
    heartRate: 78,
    respiratoryRate: 18,
    bloodOxygen: 97,
    weight: 65,
    height: 165,
    bmi: 23.9,
    notes: "Slight fever, monitor closely",
  },
]

// Mock nursing tasks
export const mockNursingTasks: NursingTask[] = [
  {
    id: "task1",
    patientId: "p1",
    patientName: "John Doe",
    taskType: "medication",
    description: "Administer antibiotic injection",
    priority: "high",
    status: "pending",
    assignedTo: "n1",
    dueDate: "2025-10-05",
    dueTime: "11:00 AM",
    notes: "IV administration required",
  },
  {
    id: "task2",
    patientId: "p2",
    patientName: "Jane Smith",
    taskType: "vitals",
    description: "Check vitals and record",
    priority: "medium",
    status: "in-progress",
    assignedTo: "n1",
    dueDate: "2025-10-05",
    dueTime: "02:00 PM",
  },
  {
    id: "task3",
    patientId: "p1",
    patientName: "John Doe",
    taskType: "wound-care",
    description: "Change wound dressing",
    priority: "high",
    status: "pending",
    assignedTo: "n2",
    dueDate: "2025-10-05",
    dueTime: "03:00 PM",
    notes: "Use sterile gauze, apply antibiotic ointment",
  },
]

// Mock medications
export const mockMedications: Medication[] = [
  {
    id: "med1",
    name: "Lisinopril",
    genericName: "Lisinopril",
    dosage: "10mg",
    form: "tablet",
    quantity: 500,
    manufacturer: "Pharma Inc",
    batchNumber: "B123456",
    expiryDate: "2025-12-31",
    price: 0.5,
    instructions: "Take once daily with water",
    sideEffects: ["Dizziness", "Dry cough"],
  },
  {
    id: "med2",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    dosage: "500mg",
    form: "capsule",
    quantity: 800,
    manufacturer: "Global Meds",
    batchNumber: "B123457",
    expiryDate: "2025-11-15",
    price: 0.3,
    instructions: "Take twice daily with food",
    sideEffects: ["Nausea", "Rash"],
  },
  {
    id: "med3",
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    dosage: "200mg",
    form: "tablet",
    quantity: 1200,
    manufacturer: "Pain Relief Co",
    batchNumber: "B123458",
    expiryDate: "2026-01-20",
    price: 0.15,
    instructions: "Take as needed for pain",
    sideEffects: ["Stomach upset", "Headache"],
  },
]

// Mock pharmacy orders
export const mockPharmacyOrders: PharmacyOrder[] = [
  {
    id: "order1",
    prescriptionId: "rx1",
    medicationId: "med1",
    medicationName: "Lisinopril 10mg",
    quantity: 30,
    refills: 2,
    status: "ready",
    prescribedDate: "2025-09-15",
    dispensedDate: "2025-09-16",
    expiryDate: "2025-12-15",
    pharmacistId: "ph1",
    patientId: "p1",
    patientName: "John Doe",
    price: 15.0,
  },
  {
    id: "order2",
    prescriptionId: "rx2",
    medicationId: "med2",
    medicationName: "Amoxicillin 500mg",
    quantity: 21,
    refills: 0,
    status: "pending",
    prescribedDate: "2025-10-01",
    pharmacistId: "ph1",
    patientId: "p2",
    patientName: "Jane Smith",
    price: 6.3,
  },
]

// Mock ambulance requests
export const mockAmbulanceRequests: AmbulanceRequest[] = [
  {
    id: "amb-req1",
    patientId: "p1",
    patientName: "John Doe",
    patientPhone: "+1-555-0101",
    pickupLocation: "123 Main Street, Apartment 5B",
    dropLocation: "Central Hospital, Emergency Wing",
    reason: "Chest pain and difficulty breathing",
    priority: "critical",
    status: "en-route",
    requestedAt: "2025-10-05 08:15 AM",
    estimatedArrival: "08:22 AM",
    driverId: "ad1",
    driverName: "Mark Johnson",
    ambulanceNumber: "AMB-001",
    ambulanceId: "amb1",
    notes: "Patient conscious, stable vitals",
  },
  {
    id: "amb-req2",
    patientId: "p3",
    patientName: "Robert Wilson",
    patientPhone: "+1-555-0102",
    pickupLocation: "789 Oak Avenue, Suite 200",
    dropLocation: "Central Hospital, General Ward",
    reason: "Fractured leg after fall",
    priority: "high",
    status: "assigned",
    requestedAt: "2025-10-05 09:30 AM",
    driverId: "ad2",
    driverName: "Sarah Connor",
    ambulanceNumber: "AMB-002",
    ambulanceId: "amb2",
    notes: "Immobilize leg, monitor for shock",
  },
  {
    id: "amb-req3",
    patientId: "p4",
    patientName: "Emily Brown",
    patientPhone: "+1-555-0103",
    pickupLocation: "456 Pine Road, Building C",
    dropLocation: "Central Hospital, OB-GYN Ward",
    reason: "Labor pains, ready to deliver",
    priority: "critical",
    status: "requested",
    requestedAt: "2025-10-05 10:45 AM",
    notes: "Pregnant patient, 38 weeks, regular contractions",
  },
]

// Mock ambulances
export const mockAmbulances: Ambulance[] = [
  {
    id: "amb1",
    ambulanceNumber: "AMB-001",
    driverId: "ad1",
    driverName: "Mark Johnson",
    driverPhone: "+1-555-1001",
    location: "Downtown District",
    status: "en-route",
    equipment: ["Oxygen tank", "Defibrillator", "Stretcher", "First aid kit", "Cardiac monitor"],
    lastServiceDate: "2025-09-15",
    nextServiceDate: "2025-11-15",
    capacity: 2,
    fuelLevel: 85,
    totalTrips: 342,
  },
  {
    id: "amb2",
    ambulanceNumber: "AMB-002",
    driverId: "ad2",
    driverName: "Sarah Connor",
    driverPhone: "+1-555-1002",
    location: "North West Zone",
    status: "available",
    equipment: ["Oxygen tank", "Defibrillator", "Stretcher", "First aid kit", "Suction device"],
    lastServiceDate: "2025-09-20",
    nextServiceDate: "2025-11-20",
    capacity: 2,
    fuelLevel: 92,
    totalTrips: 298,
  },
  {
    id: "amb3",
    ambulanceNumber: "AMB-003",
    driverId: "ad3",
    driverName: "David Martinez",
    driverPhone: "+1-555-1003",
    location: "Central Station",
    status: "available",
    equipment: ["Oxygen tank", "Defibrillator", "Stretcher", "First aid kit", "Blood pressure kit"],
    lastServiceDate: "2025-10-01",
    nextServiceDate: "2025-12-01",
    capacity: 2,
    fuelLevel: 78,
    totalTrips: 267,
  },
]

// Mock ambulance trips
export const mockAmbulanceTrips: AmbulanceTrip[] = [
  {
    id: "trip1",
    ambulanceId: "amb1",
    ambulanceNumber: "AMB-001",
    driverId: "ad1",
    driverName: "Mark Johnson",
    patientId: "p1",
    patientName: "John Doe",
    pickupLocation: "123 Main Street",
    dropLocation: "Central Hospital Emergency",
    startTime: "2025-10-04 14:30",
    endTime: "2025-10-04 14:45",
    distance: 5.2,
    fare: 45.0,
    status: "completed",
  },
  {
    id: "trip2",
    ambulanceId: "amb2",
    ambulanceNumber: "AMB-002",
    driverId: "ad2",
    driverName: "Sarah Connor",
    patientId: "p2",
    patientName: "Jane Smith",
    pickupLocation: "456 Oak Avenue",
    dropLocation: "Central Hospital General Ward",
    startTime: "2025-10-04 16:15",
    endTime: "2025-10-04 16:35",
    distance: 8.7,
    fare: 65.0,
    status: "completed",
  },
]