import type { Appointment, MedicalRecord, Bill } from "./types"

export const mockBills = [
  { id: 1, patient: "John Doe", total: 120.0, status: "paid", date: "2025-11-20" },
  { id: 2, patient: "Jane Smith", total: 250.0, status: "pending", date: "2025-11-21" },
  { id: 3, patient: "Bob Johnson", total: 75.5, status: "paid", date: "2025-11-22" },
  { id: 4, patient: "Alice Brown", total: 180.0, status: "pending", date: "2025-11-22" },
]
// Mock appointments data
export const mockAppointments: Appointment[] = [
  {
    appointment_id: "apt1",
    patientId: "p1",
    patientname: "John Doe",
    doctorId: "d1",
    doctor_name: "Dr. Sarah Smith",
    appointment_date: "2025-10-05",
    time: "10:00 AM",
    appointment_type: "consultation",
    status: "scheduled",
    reason: "Regular checkup",
    start_time: "10:00 AM",
    end_time: "10:30 AM",
  },
  {
    appointment_id: "apt2",
    patientId: "p2",
    patientname: "Jane Doe",
    doctorId: "d2",
    doctor_name: "Dr. Mark Lee",
    appointment_date: "2025-10-05",
    time: "11:00 AM",
    appointment_type: "consultation",
    status: "scheduled",
    reason: "Follow-up",
    start_time: "11:00 AM",
    end_time: "11:30 AM",
  },
]

// Mock medical records
export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "mr1",
    patientId: "p1",
    patientName: "John Doe",
    doctorId: "d1",
    date: "2025-09-15",
    diagnosis: "Hypertension Stage 1",
    symptoms: ["Headache", "Dizziness", "Fatigue"],
    prescription: [
      {
        id: "rx1",
        medication: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        instructions: "Take in the morning with water",
      },
    ],
    labResults: [
      {
        id: "lab1",
        testName: "Blood Pressure",
        result: "145/92 mmHg",
        normalRange: "120/80 mmHg",
        date: "2025-09-15",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to reduce sodium intake and increase physical activity.",
    followUpDate: "2025-10-15",
  },
  {
    id: "mr2",
    patientId: "p2",
    patientName: "Jane Smith",
    doctorId: "d2",
    date: "2025-08-20",
    diagnosis: "Type 2 Diabetes",
    symptoms: ["Increased thirst", "Frequent urination", "Fatigue"],
    prescription: [
      {
        id: "rx2",
        medication: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "60 days",
        instructions: "Take with meals",
      },
    ],
    labResults: [
      {
        id: "lab2",
        testName: "Fasting Blood Sugar",
        result: "140 mg/dL",
        normalRange: "70-100 mg/dL",
        date: "2025-08-20",
        status: "abnormal",
      },
      {
        id: "lab3",
        testName: "HbA1c",
        result: "7.2%",
        normalRange: "< 6.5%",
        date: "2025-08-20",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to follow a low-sugar diet and exercise regularly.",
    followUpDate: "2025-09-20",
  },
  {
    id: "mr3",
    patientId: "p3",
    patientName: "Michael Johnson",
    doctorId: "d1",
    date: "2025-11-10",
    diagnosis: "Common Cold",
    symptoms: ["Cough", "Sneezing", "Sore throat"],
    prescription: [
      {
        id: "rx3",
        medication: "Paracetamol",
        dosage: "500mg",
        frequency: "Every 6 hours",
        duration: "5 days",
        instructions: "Take after meals",
      },
    ],
    labResults: [],
    notes: "Rest and hydration recommended.",
    followUpDate: "2025-11-15",
  },
  {
    id: "mr4",
    patientId: "p4",
    patientName: "Emily Davis",
    doctorId: "d3",
    date: "2025-07-12",
    diagnosis: "Asthma",
    symptoms: ["Shortness of breath", "Wheezing", "Chest tightness"],
    prescription: [
      {
        id: "rx4",
        medication: "Albuterol Inhaler",
        dosage: "2 puffs",
        frequency: "As needed",
        duration: "30 days",
        instructions: "Use during asthma attacks",
      },
    ],
    labResults: [],
    notes: "Patient advised to avoid allergens and monitor peak flow.",
    followUpDate: "2025-08-12",
  },
  {
    id: "mr5",
    patientId: "p5",
    patientName: "William Brown",
    doctorId: "d2",
    date: "2025-06-18",
    diagnosis: "Hyperlipidemia",
    symptoms: ["Fatigue", "Xanthomas"],
    prescription: [
      {
        id: "rx5",
        medication: "Atorvastatin",
        dosage: "20mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Take in the evening",
      },
    ],
    labResults: [
      {
        id: "lab4",
        testName: "Cholesterol",
        result: "240 mg/dL",
        normalRange: "< 200 mg/dL",
        date: "2025-06-18",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to reduce dietary fats and exercise.",
    followUpDate: "2025-09-18",
  },
  {
    id: "mr6",
    patientId: "p6",
    patientName: "Olivia Wilson",
    doctorId: "d1",
    date: "2025-05-10",
    diagnosis: "Migraine",
    symptoms: ["Severe headache", "Nausea", "Sensitivity to light"],
    prescription: [
      {
        id: "rx6",
        medication: "Sumatriptan",
        dosage: "50mg",
        frequency: "As needed",
        duration: "30 days",
        instructions: "Take at onset of migraine",
      },
    ],
    labResults: [],
    notes: "Patient advised to maintain a headache diary.",
    followUpDate: "2025-06-10",
  },
  {
    id: "mr7",
    patientId: "p7",
    patientName: "Sophia Martinez",
    doctorId: "d3",
    date: "2025-04-05",
    diagnosis: "Anemia",
    symptoms: ["Fatigue", "Paleness", "Shortness of breath"],
    prescription: [
      {
        id: "rx7",
        medication: "Iron supplements",
        dosage: "65mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Take with vitamin C for absorption",
      },
    ],
    labResults: [
      {
        id: "lab5",
        testName: "Hemoglobin",
        result: "9 g/dL",
        normalRange: "12-16 g/dL",
        date: "2025-04-05",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to consume iron-rich foods.",
    followUpDate: "2025-07-05",
  },
  {
    id: "mr8",
    patientId: "p8",
    patientName: "Liam Garcia",
    doctorId: "d2",
    date: "2025-03-15",
    diagnosis: "Hypothyroidism",
    symptoms: ["Fatigue", "Weight gain", "Cold intolerance"],
    prescription: [
      {
        id: "rx8",
        medication: "Levothyroxine",
        dosage: "50mcg",
        frequency: "Once daily",
        duration: "60 days",
        instructions: "Take on an empty stomach",
      },
    ],
    labResults: [
      {
        id: "lab6",
        testName: "TSH",
        result: "8.5 mIU/L",
        normalRange: "0.5-4.5 mIU/L",
        date: "2025-03-15",
        status: "abnormal",
      },
    ],
    notes: "Patient advised to take medication consistently and monitor symptoms.",
    followUpDate: "2025-05-15",
  },
  {
    id: "mr9",
    patientId: "p9",
    patientName: "Noah Anderson",
    doctorId: "d1",
    date: "2025-02-10",
    diagnosis: "Gastritis",
    symptoms: ["Stomach pain", "Nausea", "Bloating"],
    prescription: [
      {
        id: "rx9",
        medication: "Omeprazole",
        dosage: "20mg",
        frequency: "Once daily",
        duration: "14 days",
        instructions: "Take before breakfast",
      },
    ],
    labResults: [],
    notes: "Patient advised to avoid spicy food and alcohol.",
    followUpDate: "2025-02-24",
  },
  {
    id: "mr10",
    patientId: "p10",
    patientName: "Ava Thomas",
    doctorId: "d3",
    date: "2025-01-05",
    diagnosis: "Seasonal Allergy",
    symptoms: ["Sneezing", "Itchy eyes", "Runny nose"],
    prescription: [
      {
        id: "rx10",
        medication: "Cetirizine",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        instructions: "Take at night",
      },
    ],
    labResults: [],
    notes: "Patient advised to avoid allergens and monitor symptoms.",
    followUpDate: "2025-02-05",
  },
];
